language: php
php:
  - '5.4'
branches:
  only:
    - master
    - prod
    - travis

before_script:
   - sudo apt-get update
   - sudo apt-get install apache2 libapache2-mod-fastcgi
   # enable php-fpm
   - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
   - sudo a2enmod rewrite actions fastcgi alias
   - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
   - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
   # configure apache virtual hosts
   - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
   # - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
   - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
   # let's look at the apache config
   - cat /etc/apache2/sites-available/default
   - sudo service apache2 restart
   # install behat
   - composer install -d tests/behat
   # init Grav
   - composer create-project getgrav/grav grav_root
   # link user directory from repo 
   - rm -rf grav_root/user && ln -s grav_root/user src/user
   - ls -l grav_root
   # install Grav
   - cd grav_root && bin/grav install
   - sudo curl localhost
   - sudo tail /var/log/apache2/access.log
   - sudo tail /var/log/apache2/error.log

script:
    # make features dir as we have not written any features yet
    - tests/behat/bin/behat --init
    - tests/behat/bin/behat -dl